metadata:
  namespace: staging
  labels:
    app: trivy
    partOf: trivy

service:
  type: NodePort
  port: 8080

image:
    repository: aquasec/trivy
    tag: 0.12.0
    pullPolicy: Always
spec:
  volumeClaimTemplates: []
  # - metadata:
  #     name: storage-name
  #   spec:
  #     storageClassName: standard
  #     accessModes: [ReadWriteOnce]
  #     resources:
  #       requests:
  #         storage: 20Gi

  replicasCout: 1
  containers:
    command: ["trivy", "server", "--listen", "0.0.0.0:8080", "--token", "8jFL@=9NyG$HHwSZ"]
    
  tolerations: []
  # - key: pool
  #   value: preemptible

  affinity: {}
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 60
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: app
    #           operator: In
    #           values:
    #           - sample
    #       topologyKey: kubernetes.io/hostname

  resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

readinessProbe:
  path: /healthz
  port: 8080
livenessProbe:
  path: /healthz
  port: 8080

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:80;
#  tls:
#    - secretName: star-kurio-me
  hosts: trivy.dendi.com
  path: /
